[package]
name = "tailcall"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "tailcall"
path = "src/main.rs"

[dependencies]
cli = {path = "cli"}
mimalloc = "0.1.39"
tokio = {version = "1.35.1",features = ["rt"]}
anyhow = "1.0.79"
exitcode = "1.1.2"

[dev-dependencies]
reqwest = "0.11.23"
serde_json = "1.0.111"
corex = {path = "corex"}
derive_setters = "0.1.6"
futures-util = "0.3.30"
pretty_assertions = "1.4.0"
serde = { version = "1.0", features = ["derive"] }
url = { version = "2", features = ["serde"] }
hyper = "0.14"
serde_yaml = "0.9"
log = "0.4.20"
env_logger = "0.11.0"
async-trait = "0.1.77"
async-graphql = { version = "7.0.1", features = [
    "dynamic-schema",
    "dataloader",
    "apollo_tracing",
] }
async-graphql-value = "7.0.1"
regex = "1.10.3"
criterion = "0.5.1"
indexmap = "2.1"
once_cell = "1.19.0"
tokio = {version = "1.35.1",features = ["fs","rt-multi-thread", "macros"]}

[workspace]
members = [".", "autogen", "cli", "cloudflare", "corex"]

[profile.release]
opt-level = 3
codegen-units = 1
panic = 'abort'
lto = 'thin'
debug = false
incremental = false
overflow-checks = false

[[bench]]
name = "json_like_bench"
harness = false

[[bench]]
name = "request_template_bench"
harness = false

[[bench]]
name = "data_loader_bench"
harness = false

[[bench]]
name = "impl_path_string_for_evaluation_context"
harness = false
