name: benchmark

on: 
  push:
    branches: 
      - ci_benchmark

  pull_request:
    types: [opened, edited]
    branches: 
      - ci_benchmark

jobs:
  benchmark:
    name: Rust project
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      # - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4

      # - name: Install stable toolchain
      #   uses: actions-rs/toolchain@v1
      #   with:
      #     toolchain: stable
      #     override: true
      #     components: rustfmt, clippy

      # - name: Cache Rust dependencies
      #   uses: actions/cache@v3
      #   with:
      #     path: |
      #       ~/.cargo/registry
      #       ~/.cargo/git
      #       target
      #     key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      # - name: Run cargo build
      #   uses: actions-rs/cargo@v1
      #   with:
      #     command: build
      #     args: --release
      
      #- name: Run tailcall
      #  run: |
      #    ./target/release/tailcall start benchmark/benchmark.graphql&

      - name: Install Nginx
        run: |
          sudo apt-get update
          sudo apt-get install -y nginx
          
      - name: Clean Up
        run: |
          sudo rm -rf /etc/nginx/sites-enabled/default

      - name: Copy Nginx Configuration
        run: |
          sudo cp .github/benchmark/nginx.conf /etc/nginx/

      - name: Test Nginx Configuration
        run: |
          sudo nginx -t

      - name: Start Nginx
        run: |
          sudo systemctl start nginx
          
      - name: Install wrk
        run: |
          sudo apt-get install -y wrk

      - id: run_wrk
        name: Run wrk
        run: |
          wrk -d 1 -t 1 -c 1 -s wrk.lua https://tailcall.fly.dev/graphql > wrk-output.txt
      
      - id: convert_wrk_output_markdown
        name: Convert output to markdown
        run: |
          node ./wrk-output-to-md.js > wrk-output.md

      # - id: add_pr_comment
      #   uses: mshick/add-pr-comment@v2
      #   with:
      #     message-path: |
      #         wrk-output.md
  
      - id: cat_wrk_output
        name: Cat output
        run: |
          cat wrk-output.md