name: Benchmark

on:
  push:
    paths-ignore: ["docs/**", "**.md"]
    branches:
      - main
  pull_request:
    paths-ignore: ["docs/**", "**.md"]
    types: [opened, reopened, synchronize, labeled]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  macro_benchmark:
    name: Macro Benchmarks
    if: "contains(github.event.pull_request.labels.*.name, 'ci: benchmark') || github.event_name == 'push'"
    runs-on: benchmarking-runner
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Install Stable Toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Run Cargo Build
        run: cargo build --release

      - name: Run Tailcall
        run: |
          TAILCALL_LOG_LEVEL=error ./target/release/tailcall start ci-benchmark/benchmark.graphql &

      - name: Install Wrk
        run: |
          sudo apt-get install -y wrk

      - name: Run Test Query
        run: |
          curl -i -X POST -d '{"query": "{posts{title}}"}' http://localhost:8000/graphql -H "Content-Type: application/json"

      - name: Warmup Wrk
        working-directory: ci-benchmark
        run: |
          wrk -d 10 -t 4 -c 100 -s wrk.lua http://localhost:8000/graphql

      - id: run_wrk
        name: Run Wrk
        working-directory: ci-benchmark
        run: |
          wrk -d 30 -t 4 -c 100 -s wrk.lua http://localhost:8000/graphql > wrk-output.txt

      - id: convert_wrk_output_markdown
        name: Convert Output to Markdown
        working-directory: ci-benchmark
        run: |
          node wrk-output-to-md.js wrk-output.txt > body.md
      - id: cat_md
        name: Cat Markdown
        working-directory: ci-benchmark
        run: |
          cat body.md

      - name: "Upload Artifact"
        uses: actions/upload-artifact@v4
        with:
          name: body
          path: ci-benchmark/body.md

  Cache_Benchmarks:
    name: Cache Micro Benchmarks result
    if: (github.event_name == 'push' && github.ref == 'refs/heads/main')
    permissions:
      pull-requests: write
      contents: write
    runs-on: benchmarking-runner
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Run Benchmarks
        run: |
          cargo install cargo-criterion rust-script
          cargo criterion --message-format=json > benches/main_benchmarks.json
          ./scripts/json_to_md.rs benches/main_benchmarks.json > benches/main_benchmarks.md
          cat benches/main_benchmarks.md

      - name: Cache Criterion Benchmarks Json
        uses: actions/cache@v4
        with:
          path: benches/main_benchmarks.json
          key: criterion_benchmarks_${{ github.sha }}

  Criterion_Compare:
    name: Comparing Micro Benchmarks
    if: "contains(github.event.pull_request.labels.*.name, 'ci: benchmark')"
    runs-on: benchmarking-runner
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Run Criterion Benchmarks
        run: |
          cargo install cargo-criterion rust-script
          cargo criterion --message-format=json > benches/benchmarks.json
          ./scripts/json_to_md.rs benches/benchmarks.json > benches/change_benchmarks.md

      - name: Print Criterion Benchmarks
        run: cat benches/change_benchmarks.md

      - name: Restore file
        uses: actions/cache@v4
        with:
          path: benches/main_benchmarks.json
          key: criterion_benchmarks_${{ github.event.pull_request.base.sha }}
          fail-on-cache-miss: true

      - name: Print Benchmark Comparision
        run: ./scripts/criterion_compare.rs benches/main_benchmarks.json benches/benchmarks.json table

      - name: Check Degradation
        run: ./scripts/criterion_compare.rs  benches/main_benchmarks.json benches/benchmarks.json check
