name: Publish on NPM
on:
  release:
    types:
      - published
permissions:
  contents: write
  pull-requests: write
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"
      - name: Update NPM version
        run: echo "Updating NPM version..."
      - run: |
          cd npm && version=${{ github.event.release.tag_name }}
          stripped_version=$(echo $version | sed 's/^v//')
          npm version $stripped_version
      - run: cd npm && npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
